### ISSUE TITLE
[Brainstorming] Données à exposer

### ISSUE THREAD

**Issue by plup** [HappyDev-team/happyWebSite#10]
Salut, 

Je créé un issue pour référencer les données des membres Happy-Dev à exposer. Je pense également que certaines d'entre elles devraient être requises alors que d'autres peuvent être optionnelles. 

Je commence par reprendre la liste de @weeger : 
- nom [requis]
- prénom [requis]
- photo [?]
- site web [option] 
- facebook [option]
- twitter [option]
- description [requis]
- techno [requis]
- réalisations [option]

A laquelle je rajouterai : 
- email [requis]
- alias [option]
- github [option]
- clef publique de chiffrement [option]

A vos remarques !

**Comment by sylvainlb** [comment]
En fait le modèle Actors de l'AV correspond presque parfaitement. Il manque la clé de chiffrement qu'on pourra ajouter dans un second temps.

**Comment by plup** [comment]
Oui, bien sûr je fais pas une fixation sur la clef de chiffrement. C'est
juste que l'idée me conforte ! ;)
Le 22 mars 2016 3:33 PM, "Sylvain Le Bon" notifications@github.com a
écrit :

**Comment by sylvainlb** [comment]
De toute façon le modèle a vocation à évoluer. On a déjà un bon début !
