### ISSUE TITLE
Utiliser la Force pour organiser les noeuds

### ISSUE THREAD

**Issue by night-gold** [HappyDev-team/happyWebSite#13]

**Comment by balessan** [comment]
Learning how to use the Force you should.

**Comment by night-gold** [comment]
@sylvainlb : Je vais avoir un problème avec les links... comme le noeud team se trouve sur autre plan, il n'est pas soumis au même jeu de coordonnées que les noeuds des membres.

**Comment by sylvainlb** [comment]
oui mais l'idée qu'on a évoqué l'autre jour était de créer un noeud invisible avec les mêmes coordonnées pour tracer les liens

**Comment by night-gold** [comment]
@sylvainlb : je suis d'accord, mais la charge s'applique aussi à se point... ainsi que la gravité... donc il se déplace inévitablement et je ne maîtrise pas ses coordonnées d'arrivées-_-... 

Je vois pas comment résoudre ce problème là, c'est pour cela que j'ai essayé d'utiliser le noeud déjà existant...

**Comment by sylvainlb** [comment]
http://stackoverflow.com/a/10400060/1224696

**Comment by night-gold** [comment]
ok, je vais pouvoir tester ça, j'était pas tombé dessus hier.

**Comment by night-gold** [comment]
@sylvainlb : yes c'était bien l'idée. J'ai carrément passé le noeud en paramètre au lieu d'envoyer le container... et ça marche pas mal... aussi avec les projets vu que le noeud sert de référence.

**Comment by happy-dev** [comment]
Désolé de ne pas encore pouvoir être d'une grande aide sur ce chantier mais... question de semaines

**Comment by sylvainlb** [comment]
@eluaneuh : ça marche avec la force, mais j'imagine qu'il faudrait changer les paramètres pour rendre l'animation plus légère. Tu en dis quoi ?

**Comment by night-gold** [comment]
En cherchant un peu j'ai testé la modification du paramètre de friction, plus on le diminue plus la "vitesse" des noeuds diminue rapidement à chaque tick... 

Avec une valeur de 0.5 de friction, les traits descendent en une fois, mais je préfère vers 0.7, ils se placent mieux.

**Comment by sylvainlb** [comment]
C'est top !
@eluaneuh : tu pourras affiner ces paramètres si tu veux
