### ISSUE TITLE
Retour à la vue principale

### ISSUE THREAD

**Issue by night-gold** [HappyDev-team/happyWebSite#14]

**Comment by sylvainlb** [comment]
@eluaneuh : A quel moment doit-on retourner à la vue principale ? Est-ce qu'on peut fermer le panneau de droite sans dézoomer ?

**Comment by ghost** [comment]
@sylvainlb : Oui, on peux fermer le panneau de droite sans dézoomer par contre bien s'assurer que le menu dans lequel l'utilisateur se situe se recentre bien par rapport à la page.

Pour retourner à la vue principale, le plus simple pour l'utilisateur, serait de voir un bouton apparaître lorsqu'il est dans un des menu. Ce bouton pourrait se détacher du haut de la page, avec un petit message explicatif qui apparait que lors de la première connexion.
Ce bouton serait visible seulement lorsque le site n'est pas dézoomer.

**Comment by sylvainlb** [comment]
Ok, tu verrais quoi pour le bouton ?
@jonathanbraley, ok pour toi ?

**Comment by ghost** [comment]
@sylvainlb : J'ai le visuel du bouton dans la tête, je vais essayer de trouver un exemple ;)

**Comment by sylvainlb** [comment]
top !

**Comment by ghost** [comment]
@sylvainlb : Sur ce site http://daneden.github.io/animate.css/ la fonction zoomOutUp pour cacher le bouton. Et transition dans le sens inverse pour le faire apparaitre.

**Comment by night-gold** [comment]
Je vais regardé ça

**Comment by night-gold** [comment]
Alors, j'arrive à dézoomer.
Maintenant, plusieurs possibilités s'offre, le panneau doit-il disparaître? les noeuds aussi?
Ou l'utilisateur conserve le panneau (tant qu'il ne l'enlève pas) et les noeuds en attendant une autre action?

@eluaneuh : Pour le visuel du bouton le même que le bouton "animate it" sur le site mais en jaune?

**Comment by sylvainlb** [comment]
J'aurais tendance à dire que quand on dézoome ça revient à l'état initial : url /, pas de panneau, pas de noeud supplémentaire.

**Comment by night-gold** [comment]
ok, je vais terminer le bouton de dezoom aujourd'hui... 

Mais il faudra surement le modifier en fonction des modif que l'on apportera dans ces issue: #6  et  #13

**Comment by night-gold** [comment]
Bouton publier sur git.

@eluaneuh : J'ai un doute sur la façon dont réapparait "happy dev" lorsque l'on dézoom, je trouve ça pas très esthetique. Tu aurais une suggestion?

**Comment by ghost** [comment]
@JonathanBraley : il faudrait déjà le ralentir. Par contre c'est vrai que c'est pas top la façon dont il réapparait. Je vais réfléchir sur comment ça pourrait bien le faire. En fait j'ai des idées mais ça risque d'être long et compliqué à écrire. Je posterai là mes idées quand j'aurais quelque chose de plus réalisable.

**Comment by night-gold** [comment]
@eluaneuh : J'ai fait un petit test et je l'ai mit sur la preview... je pense que c'est mieux au niveau de l'effet...
Par contre, j'ai du modifier le css du div du titre Happy dev... maintenant il est vraiment centrer sur la page et ça décale légérement...

**Comment by sylvainlb** [comment]
Laisser le logo en petit en mode zoomé identique au gros
