### ISSUE TITLE
Rendre ça beau

### ISSUE THREAD

**Issue by night-gold** [HappyDev-team/happyWebSite#16]

**Comment by ghost** [comment]
Centrer le nom du membre Happy-Dev sous le petit rond qui lui appartient
Changer la police, cette alternative me paraît être la meilleur https://github.com/theleagueof/league-gothic
Couleur de fond possible allant avec le jaune : 

312E22 
393731 
3D3C37 
4E4C45 
646157 

Sur la fiche d'un membre/projet, une croix dans un rond pour la fermeture de l'onglet, qui se tourne à 45 ou 90°C sur la droite avec effet de transition. Croix blanche sur fond (couleur identique au background du body) lors d'un :hover. Couleur inversé si pas :hover.

L'ouverture et la fermeture de l'onglet avec effet de transition, que le tout soit fluide et dynamique. 300 à 500 ms, à voir.

L'user est sur « team », il clique sur « projets », les ronds de « team » se ferment tandis que ceux de « projets » s'ouvrent. Si ça peux se faire simultanément, c'est plus fun, sinon c'est pas grave, ça peut tout aussi bien être une action après l'autre.

Au clic d'un menu, le centrer sur la page, penser à le faire aussi lorsque l'onglet est déroulé.
Au clic d'un menu, centrer dessus avec les ronds qui apparaissent.

Rendre les « fill » entièrement cliquable, faire passer les « stroke » en dessous.
Rendre le logo et la phrase de présentation cliquable. Au clic, une popup affichant le manifeste.

**Comment by sylvainlb** [comment]
@eluaneuh : il faut trancher sur la couleur et tester avec la police, voir avec @JonathanBraley
