### ISSUE TITLE
Rajouter le manifeste

### ISSUE THREAD

**Issue by night-gold** [HappyDev-team/happyWebSite#17]

**Comment by night-gold** [comment]
J'ai préparé l'affichage du manifeste.
Pour les données à mettre dedans, il y'a quelque chose de déjà prêt ou je publie juste comme ça pour le moment?

**Comment by night-gold** [comment]
Manifeste ajouté sur git.

**Comment by sylvainlb** [comment]
Petit bug graphique, mais c'est un bon début.
J'ai le sentiment qu'on ne pensera pas à cliquer

**Comment by night-gold** [comment]
@sylvainlb : Tu as quoi comme bug??
On peut toujours rajouté un autre effet graphique en plus du cursor si besoin.
