### ISSUE TITLE
Corrections Mep

### ISSUE THREAD

**Issue by ghost** [HappyDev-team/happyWebSite#18]
Dans l'ordre d'importance :  
- Sur la vue principale et lors du zoom, les cercles doivent passer au dessus des traits et non l'inverse.
- Si on garde les noms sous les cercles, faire aussi passer les traits sous les noms.

C'est 2 points sont indispensables car un utilisateur voulant cliquer sur un de ces éléments peux malencontreusement cliquer sur le trait et se dire "ça ne fonctionne pas".
- La lettre X, on est d'accord, c'est une barre qui part d'en haut à gauche et qui se fini en bas à droite. Et une autre barre qui part d'en haut à droite et qui se fini en bas à gauche en croisant le première barre en son centre. Lors du croisement des 2 barres, l'angle se situant entre chaque croisement doit être égale à 45° (pas 90 comme je l'ai indiqué auparavant) Or dans la lettre X, l'angle en haut et en bas de ce croisement et inférieur à 45° et l'angle à droite et à gauche de ce croisement est supérieur à 45°.
  - Ensuite cette même croix, la centrer dans le rond. Et mettre un fond blanc au rond. (le fond doit avoir la même couleur que la background-color du body). Puis pour donner un petit côté cool, au passage de la souris dessus (mettre un cursor pointer) et le faire tourner à 90° vers la droite (l'utilisateur amenant sa souris de la gauche vers la droite, ce mouvement vers la droite suit la continuité naturel du mouvement)
  - Mettre un background-color #FFF et une cursor pointer lors d'un hover pour les cercles de fermeture.

@sylvainlb @JonathanBraley

**Comment by night-gold** [comment]
@eluaneuh : j'ai fait un test avec l'unicode pour un symbole de croix, je trouve que c'est pas trop mal.

**Comment by sylvainlb** [comment]
La croix bugue chez moi, sous linux. Est-ce un problème de police ?

**Comment by night-gold** [comment]
@eluaneuh : j'ai remplacer le symbole de croix que j'avais trouvé, il ne marchait que sous windows... Et comme je ne trouve rien qui s'affiche de la même manière sous tous les navigateurs... j'ai collé un png pour l'instant.

**Comment by ghost** [comment]
Cool pour le mouvement. Il faut faire attention que le cercle entourant la croix ne se déplace pas lors du passage de la souris sur celui-ci. Actuellement il se déplace légèrement vers la gauche.

**Comment by night-gold** [comment]
Oui, j'ai vu ça... Mais je vois pas pourquoi ça le fait...
Il faut apporter les corrections de position en même temps que le mouvement?

**Comment by ghost** [comment]
@JonathanBraley : Je me suis pas penché sur la question mais je regarde ça plus tard si tu veux. Plus tard = demain.

**Comment by night-gold** [comment]
@eluaneuh : j'ai refait des test ce matin... et j'ai tester avec  l'outil de positionnement de firefox, mais en fait l'image bouge pas... 

J'ai l'impression que c'est juste de l'illusion d'optique le mouvement qu'on perçoit...

**Comment by sylvainlb** [comment]
En fait c'est que le rond n'est pas centré dans l'image.
Je pense que pour l'instant c'est pas grave, mais c'est un argument de plus
pour utiliser un caractère après la mep.
