### ISSUE TITLE
Panel Team

### ISSUE THREAD

**Issue by ghost** [HappyDev-team/happyWebSite#19]
- Sur le panel Team, au passage de la souris sur le prénom, nom et photo du membre, mettre un cursor pointeur et les rendre cliquable. Destination : fiche personnel du membre.

**Comment by night-gold** [comment]
@sylvainlb : J'ai tester ça aujourd'hui...Mais je ne comprend pas comment sont passer les variables à la fonction showMembers.
J'ai essayer différentes choses mais, je n'arrive pas à repasser en paramètre l'objet membre dans la liste. j'ai commencer à lire la doc sur les handlebars, mais j'ai rien trouvé pour passer l'objet actuel entier en paramètre... 
Je n'arrive pas non plus à récupéré uniquement l'id... je dois mal m'y prendre...

**Comment by night-gold** [comment]
J'en ai profité pour le faire sur le panel projects aussi.
