### ISSUE TITLE
Séparation panel et site

### ISSUE THREAD

**Issue by ghost** [HappyDev-team/happyWebSite#21]
- Le trait noir de séparation entre le panel des membres et le reste du site. Je pense à deux possibilités. Soit le rendre identique d'un point de vue épaisseur et couleur que les traits spérant les membres dans le panel. Soit le laisser tel quel en lui donnant un léger effet 3D/ de profondeur sur le côté gauche. Ce qui aura pour effet visuel de surélever légèrement le panel par rapport au reste du site.

**Comment by night-gold** [comment]
@eluaneuh : J'ai décidé de tester la première solution pour le moment.
Je test aussi avec les effets 3D de bordure... Mais ils sont pas tip top avec un seul bord...
