### ISSUE TITLE
Centrer lors du zoom

### ISSUE THREAD

**Issue by ghost** [HappyDev-team/happyWebSite#23]
- Au clic de Team et donc à l'ouverture du panel avec les membres de la team, centrer le gros rond Team par rapport à la bordure gauche et à la bordure droite (celle faisant les délimitation du panel et du reste du site).

**Comment by sylvainlb** [comment]
Sauf que quand on ferme le panel on se retrouve en plein écran et du coup ça n'a plus de sens de décentrer le point.
Si on se fie au design, il faut au contraire relier le point au panel avec un trait et donc le décentrer près du panel

**Comment by ghost** [comment]
Ok, je cloture cette issue.
