### ISSUE TITLE
Fiche membre, placement du prénom/nom

### ISSUE THREAD

**Issue by ghost** [HappyDev-team/happyWebSite#24]
- Sur une fiche membre, décaler le prénom de la bordure gauche. Mettre autant de pixels entre le bas de la photo et le prénom/nom qu'entre le prénom et la bordure de gauche.

**Comment by sylvainlb** [comment]
@JonathanBraley : voir le design d'arnaud sur ce point

**Comment by night-gold** [comment]
@sylvainlb : Pas de soucis. 

Pour les projets, je fais la même chose aussi? J'avais fait un test pour faire plus propre en attendant... Mais je peut les modifier aussi pendant que j'y suis ^^
