### ISSUE TITLE
Déplacement entre menus

### ISSUE THREAD

**Issue by ghost** [HappyDev-team/happyWebSite#26]
- Lorsque le site est zoomer, pouvoir se déplacer sur entre les différents gros ronds en cliquant sur le background du site avec le clic gauche, en le maintenant enfoncé et en poussant la souris dans la direction choisie.

**Comment by sylvainlb** [comment]
Je passe cette issue en post mep, parce que je pense que ça n'est pas bloquant

**Comment by ghost** [comment]
Bloquant non mais emmerdant et pas clair pour l'utilisateur oui.

Pour nous, qui savons, il faut cliquer sur le logo en haut à gauche pour revenir à la vue principale puis à nouveau sur le menu de notre choix. Or l'utilisateur lambda (qui peux être un gros débile), une fois un menu fermé, aura tendance à se demander comment on accède aux autres menus. Car ni le déplacement dans la page n'est pas possible par la souris ni par les flèches directionnelles.

Là c'est mon avis perso en me mettant à la place de l'utilisateur.

**Comment by sylvainlb** [comment]
Du coup il faut rendre plus clair qu'on peut revenir au menu en cliquant sur le logo en haut à gauche

**Comment by ghost** [comment]
ça je pense que c'est clair. Ce qui n'est pas clair c'est de devoir revenir à la page principale pour accéder à un autre menu. Ce n'est pas logique. D'où la nécessité de mettre en place la navigation à la souris ou avec les flèches directionnelles avec la mep.

**Comment by sylvainlb** [comment]
Je vois pas où est le problème. Quand on navigue dans un site il y a un
menu et on retourne au menu pour aller dans d'autres sections.
Ce que tu proposes est cool, mais restons simple pour l'instant, sinon on
ne mettra jamais en prod.

**Comment by ghost** [comment]
Oui, c'est peut-être moi et ma manie du détails dans le travail qui me joue des tours :D 
Faisons ça après la mise en prod et entre temps verra le retour utilisateur.

**Comment by sylvainlb** [comment]
Hehe, good enough, c'est la clé de l'agilité !
Quand on aura good enough en prod, on pourra chercher à améliorer :)
