### ISSUE TITLE
Centrer prénom/nom sous cercle mue par la force

### ISSUE THREAD

**Issue by ghost** [HappyDev-team/happyWebSite#27]
- Centrer le prénom et le nom en dessous du cercle (prendre en compte que chaque prénom et nom diffère en longueur).

**Comment by night-gold** [comment]
@eluaneuh : Je regarde ça depuis un moment... Et le problème qu'il y'a c'est que le rond n'est pas centré... Il lui a été donné une position arbitraire, le texte lui est centré en fait... Puisque le conteneur svg dans lequel il est à sa taille...
Là j'avoue que je voit pas trop comment faire... Car, si je bouge le cercle, il faut refaire tous les calculs mais ça ne résoudra pas le problème et je ne trouve pas le moyen de récupéré le width de chaque texte pour tenter de le placer en fonction de sa longueur...

**Comment by sylvainlb** [comment]
Tu peux mettre une taille fixe à la boite, mais alors si le nom est trop
long il ne rentrera pas.

**Comment by night-gold** [comment]
J'ai pensé la même chose... Je suis en train de reprendre avec le site du stephen hawking effect... Ils ont réussi à le faire avec un text-anchor middle... ce qui semble marché aussi pour le site...
Mais c'est là que c'est fort.. le svg ne supporte pas qu'on touche à sa limite gauche... Je me retourve donc avec le nom centré mais à moitié invisible et un quart de cercle...
Si je trouve d'ou vient le problème ça se fera tout seul...

**Comment by night-gold** [comment]
@sylvainlb , @eluaneuh : Je viens de trouver quelque chose qui marche... Je met en ligne mes modifications...

Je ne sais juste pas ce que ça pourrait donner avec des personnes qui ont des noms vraiment très long... Mais pour ceux déjà présent ça semble marcher.
