### ISSUE TITLE
Apparence du formulaire de contact

### ISSUE THREAD

**Issue by sylvainlb** [HappyDev-team/happyWebSite#30]

**Comment by ghost** [comment]
Pour le chargement des éléments, je propose quelque chose dans le genre : http://bit.ly/1roPaG0
Une fois sur cette page, cliquez sur "recommencer" puis "commencer", une fois les informations séléctionnés/rentrés, la seconde question apparait avec fluidité.

Pas de texte jaune sur le fond blanc, noir ou légèrement grisé.
Aligné verticalement les questions, réponses et input.
Passer les input sous les questions.

Voyons déjà voir le résultat avec ces modifications.
