### ISSUE TITLE
Données sur les fiches

### ISSUE THREAD

**Issue by sylvainlb** [HappyDev-team/happyWebSite#31]
Il faudrait faire la liste des données obligatoires sur les fiches de membres et de projets, et les faire rentrer par les membres

**Comment by ghost** [comment]
A mon avis les infos importantes :
- Ville
- Disponible / pas disponible. Sous forme de pastille coloré, le plus évident vert et rouge. Où on peux imposer nos codes. #FDC815 disponible, #2F25B0 indisponible. (C'est notre jaune et sa couleur opposé)
- Les technos que nous maîtrisont (pas de limite du nombre de technos) avec un système d'affichage des 10/15/20 (nombre à définir) technos les mieux maîtrisés en avant. Puis un "afficher la suite" pour dérouler les autres compétences. C'est pour éviter l'affichage d'un paquet monstre en une fois.
  - Dans ces technos maitrisés, Une petite icône (dynamique ou non, à voir) qui définit notre niveau de maîtrise.
  - Pour l'image définissant notre niveau de maîtrise de nos compétences, je propose une idée de concept basé sur l'idée de points et traits qui se rejoignent (voir les images attachés, c'est fait à l'arrache juste pour l'idée, faites pas gaffe aux détails :P). 
    ![2_sur_5](https://cloud.githubusercontent.com/assets/17434731/14710559/1b6b235e-07d6-11e6-93d3-c1abb2cc35d5.png)
    ![5_sur_5](https://cloud.githubusercontent.com/assets/17434731/14710558/1b6aab72-07d6-11e6-9aca-f82a03d566fb.png)
    Un trait = débutant
    Deux traits = intérmédiaire
    trois traits = confirmé
    quatre traits = expert
    cinq traits = Chuck Norris
- Avant l'affichage du membre, sur le panel Team, sous chaque prénom/nom afficher les 3 technos que nous voulons mettre en avant / ou qui nous définissent le mieux.
