### ISSUE TITLE
Ajouter une transition sur l'ouverture et fermeture du panel

### ISSUE THREAD

**Issue by sylvainlb** [HappyDev-team/happyWebSite#32]

**Comment by night-gold** [comment]
@eluaneuh : je suis pas contre un exemple de code pour l'effet que tu nous avais montré....
Parce que le code que je trouve pour l'instant, je n'arrive pas à le faire fonctionner...

**Comment by night-gold** [comment]
J'ai trouvé un truc qui s'appel "oridomi", c'est un librairie js pour faire des effets et y'en à un de paperfold qui marche horizontalement... Jusque là tout va bien... Le soucis c'est qu'une fois cet effet appliqué, le panel se trouve en décalage avec le top right... Malgré des valeurs à zéro... Et je n'arrive pas à le remettre comme il faut...
