### ISSUE TITLE
Corriger l'apparence du manifeste

### ISSUE THREAD

**Issue by sylvainlb** [HappyDev-team/happyWebSite#33]
@eluaneuh : comment peut-on rendre le manifeste un peu plus beau ?

**Comment by ghost** [comment]
list-style-type à none
Centrer toutes les lignes
Ne pas justifier le texte

Le texte ne peux pas être jaune, ça passe très mal avec le blanc, sur l'écran en tout cas.
Le nom des membres dans le panel Team n'est pas en jaune mais en noir. Il faut faire pareil ici afin de garder une certaine homogénéité et cohérence visuel pour les visiteurs du site.

Griser légèrement chaque paragraphe (en #1a1a1a par exemple) et au passage de la souris sur chaque paragraphe, le passer en #000000.
