### ISSUE TITLE
Donner taille fixe panel durant action ouvrir/fermer

### ISSUE THREAD

**Issue by ghost** [HappyDev-team/happyWebSite#35]
Sur Projects, lors de la fermeture/ouverture du panel, la liste des projets au moment d'approcher de la bordure droite se casse légèrement la gueule. Les éléments se redimensionne puisque la fenêtre diminue en largeur. Il faudrait lors de l'action de la fermeture donner une taille fixe en pixels à ces éléments
Il en va de même pour Team, même si cela se voit moins.

**Comment by night-gold** [comment]
J'ai changer l'animation, au lieu d'un hide, je fais un animate en jquery.
