### ISSUE TITLE
Bug #4 ?

### ISSUE THREAD

**Issue by ghost** [HappyDev-team/happyWebSite#41]
Pas sûr que cela soit un bug, c'est peut-être voulu ?

Lorsqu'on clic sur le gros cercle "Team", zoom + panel Team qui s'ouvre. Lorsqu'on ferme le panel Team, en cliquant à nouveau sur le gros cercle "Team" aucune action n'est executé.

**Comment by night-gold** [comment]
Effectivement... Bug... oui et non... c'est un problème avec crossroads, il mémorise la dernière route utilisée et tant qu'il n'a pas utilisé une autre route, il ne relance pas l'action (pas la peine, il est déjà au bon endroit.

Je corrige la fonction appelé par les noeuds au clic...

**Comment by night-gold** [comment]
J'ai corrigé le problème...

L'animation ne se relance pas, mais c'est pas plus mal au final... ca corrige aussi le bug du multiclick.
