### ISSUE TITLE
Affichage Titre projet/nom membre 

### ISSUE THREAD

**Issue by ghost** [HappyDev-team/happyWebSite#42]
Dans le cas où le titre d'un projet ou bien le nom du membre est trop long. C'est le cas avec le mien :P 
Donner une largeur fixe au contenu du titre/nom et le faire descendre à la ligne si celui-ci est trop long afin de ne pas casser le style. Penser à le couper au niveau d'un espace et non en plein milieu d'un mot.

**Comment by sylvainlb** [comment]
css sait très bien faire ça. Pas besoin de js ici

**Comment by night-gold** [comment]
Modification effectuée
