### ISSUE TITLE
Fermer la popup de contact après validation

### ISSUE THREAD

**Issue by sylvainlb** [HappyDev-team/happyWebSite#46]
Lorsqu'on valide le formulaire de contact, il faudrait vider la popup, écrire, merci, à bientôt et faire disparaître la popup en fade out

**Comment by night-gold** [comment]
@sylvainlb : J'ai mit un formulaire de contact refait sur la preview.

**Comment by MarjolaineLB** [comment]
quand on valide, la dernière étape, on a bien merci, à bientôt tout ça.
il y a aussi écrit (envoyer) -> il faut bien cliquer dessus pour que le message parte ? En tous cas c'est comme ça que je l'ai compris.

**Comment by night-gold** [comment]
oui c'est ça pour l'instant. Tant que la personne n'a pas cliqué, le message ne part pas... Je maîtrise pas encore trop bien la pop-up de remerciement... Elle est trop sale à l'affichage, c'est une modification qu'il faudra que je fasse après.
