### ISSUE TITLE
formatage du texte

### ISSUE THREAD

**Issue by MarjolaineLB** [HappyDev-team/happyWebSite#48]
Prévoir un formatage automatique du texte pour éviter les disparités et garder une certaine cohérence.
Exemple : Amandine est la seule à avoir son nom de famille en majuscule, il faudrait qu'il puisse être automatiquement appliqué en minuscule comme pour les autres.

**Comment by sylvainlb** [comment]
pas faisable en css finalement. @balessan : Est-ce qu'il y a une solution liée à WPLDP ?
Sinon on laisse tomber et on repart sur la solution du fouet :)

**Comment by balessan** [comment]
Ben on peut traiter la chaine de caractere qui vous interesse avant de l'afficher mais ça nécessite de passer par un beau : 

```
 if ($field->name === 'nom_du_champ') blabla...
```

Pas sûr que ce soit idéal...

**Comment by night-gold** [comment]
@balessan : et faire le traitement à l'enregistrement de la donnée? ça demanderas de repasser sur ceux qui sont pas au bon format pour l'instant... Mais pour les suivant le problème ne se représenteras pas...

**Comment by balessan** [comment]
Nah, trop spécifique à votre besoin. Sur quel critère je me base pour savoir que tel champ doit être normalisé ?

Faut pas oublier qu'on veut conquérir le monde, et qu'il y a sûrement des gens qui voudront écrire leur nom en SnaKeCaSe :p

**Comment by MarjolaineLB** [comment]
on va devoir rester sur la solution de la correction manuelle au cas par cas et du fouet alors....

**Comment by sylvainlb** [comment]
Effectivement. Dommage que le text-transform capitalize ne fasse pas l'affaire.
