### ISSUE TITLE
popup de contact - partie Qu'est-ce que je peux faire pour toi ?

### ISSUE THREAD

**Issue by MarjolaineLB** [HappyDev-team/happyWebSite#49]
est-il envisageable de permettre à l'espace de saisie de s'agrandir au fur et à mesure de la saisie ?

Je trouve ça assez inconfortable de ne pas voir l'ensemble de ma requête, ne serait-ce que pour pouvoir me relire avant d'envoyer...

**Comment by sylvainlb** [comment]
En tout cas le champ requête est clairement trop petit
