### ISSUE TITLE
Envoi de mail

### ISSUE THREAD

**Issue by balessan** [HappyDev-team/happyWebSite#5]
Être capable d'envoyer un mail depuis l'interface en JavaScript.

Une stratégie: Envoi d'une commande sur une URL dédié qui répondra via Wordpress et enverra un mail.

**Comment by sylvainlb** [comment]
@jonathanfallon  @balessan : une idée d'implémentation côté wordpress ?

**Comment by jonathanfallon** [comment]
Via `admin-ajax.php` et le système de hooks de WordPress pour gérer l'AJAX.
La fonction `wp_mail()` te permets d'envoyer facilement des emails.

**Comment by sylvainlb** [comment]
@balessan : est-ce que ça a du sens de faire ça sur wpldp ? Sinon il faut créer un nouveau package ?

**Comment by balessan** [comment]
J'approuve ce que dit Jonathan (je ne connais les possibilités
d'admin-ajax.php que depuis peu) et je pense qu'il faudrait gérer ça dans
un autre package, ç'est très spécifique.

2016-04-12 17:18 GMT+02:00 Sylvain Le Bon notifications@github.com:

> @balessan https://github.com/balessan : est-ce que ça a du sens de
> faire ça sur wpldp ? Sinon il faut créer un nouveau package ?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/HappyDev-team/happyWebSite/issues/5#issuecomment-208957983

## 

Benoît ALESSANDRONI

_Web developer / développeur Web_
Tél: 06 35 51 64 64

**Comment by sylvainlb** [comment]
Du coup il faudrait faire un package pour le site d'Happy Dev ? Est-ce que quelqu'un qui a des compétences wordpress peut nous faire un premier jet ?

**Comment by happy-dev** [comment]
Je peux mais pas tout de suite. 
Ça vaut le coup de demander à Sébastien. Mine de rien il contribue pas mal sur les sujets techniques
