### ISSUE TITLE
Utiliser des web components

### ISSUE THREAD

**Issue by sylvainlb** [HappyDev-team/happyWebSite#50]
Les éléments ne faisant pas partie du graphe devraient être fournis sous forme de web components

**Comment by night-gold** [comment]
@sylvainlb : on crée une branche dans git pour cette version du site ou on fait ça directement sur la preview?

**Comment by sylvainlb** [comment]
on peut utiliser dev et le site de preview

2016-05-11 12:47 GMT+02:00 JonathanBraley notifications@github.com:
