### ISSUE TITLE
photo dans les ronds

### ISSUE THREAD

**Issue by MarjolaineLB** [HappyDev-team/happyWebSite#52]
est-il possible d'ajouter les photos dans les ronds jaunes du graphique (team/project) ?
:)

**Comment by night-gold** [comment]
@sylvainlb @MarjolaineLB : Le problème en mettant des images, c'est que je ne peut pas mettre de cercle en tant que centre. Ce qui pose le problème des traits par dessus le noeud team ou project.

C'est que le début, mais c'est le premier gros problème que je peut constater.

**Comment by sylvainlb** [comment]
En y réfléchissant, je me dis que la bonne solution est probablement de rajouter dans le svg principal un autre svg pour les noeuds temporaires, avant les circles principaux, et de mettre toutes les data venant de ldp dedans.

**Comment by night-gold** [comment]
Non, ça c'est bon, il suffit de dessiner des cercles avant de faire le clippath...
