### ISSUE TITLE
fleche directionnelle

### ISSUE THREAD

**Issue by MarjolaineLB** [HappyDev-team/happyWebSite#54]
ajouter un symbole de flêches pour rendre la navigation plus évidente pour le visiteur.
ajouter ce symbole sous le "happy dev" qui apparaît en haut à gauche.

Permettre la navigation grâce aux fleches directionnelles du clavier

**Comment by night-gold** [comment]
@MarjolaineLB : J'ai mis un test sur la preview pour l'image seulement pour l'instant.

**Comment by MarjolaineLB** [comment]
mhmmmm, pas d'image chez moi...

**Comment by night-gold** [comment]
Oups... J'ai oublié de faire le git pull hier soir
