### ISSUE TITLE
Routage dans l'application

### ISSUE THREAD

**Issue by balessan** [HappyDev-team/happyWebSite#6]
Modifier l'URL lorsqu'on modifie une zone.

Être capable de pointer directement sur la zone depuis cette URL.

Exemple: http://happy-dev.fr/projects/ pointe directement sur le listing des projets.

**Comment by night-gold** [comment]
Quelqu'un à une préférence, ou je peut tester différents produit et prendre celui que je préfère?

**Comment by night-gold** [comment]
@sylvainlb : J'arrive à faire fonctionner crossroads.js... Par contre, il semblerait que pour fonctionner la racine de l'url doivent comporter un #/ supplémentaire pour que les utilisateurs n'aient pas à le taper ou utiliser de la réécriture d'url peut-être.

Je met en ligne ce que j'ai fait, tu pourras jeter un œil.

**Comment by sylvainlb** [comment]
je pense qu'on doit pouvoir faire un petit .htaccess facilement pour ne pas utiliser le #

**Comment by night-gold** [comment]
je regarde ça...

**Comment by night-gold** [comment]
Routage mis en place. Il reste encore à déterminer de quelle façon va être mis le routage pour pouvoir atteindre un membre ou un projet spécifique.
